Repository fga-eps-mds/2024.1-PrintGo-FrontEnd, pull requests merged in 2024-09, with the labels that each got.

#70 Feature/55 dashboard
  package-lock.json
  package.json
  src/App.js
  src/components/navbar/Navbar.js
  src/pages/Dashboard.js
  src/services/dasboardService.js
  src/services/patternService.js
  src/style/pages/dashboard.css
  src/tests/pages/Dashboard.test.js
  src/tests/services/dashboardService.test.js
  src/utils/logo.js
  yarn.lock
Labels: feature

#75 [HOTFIX] Remove paginação de contratos
  src/pages/ContractList.js
  src/services/contractService.js
Labels: hotfix

#84 Release Final
  src/components/containers/StatusDropdown.js
  src/components/forms/CounterRoutineForm.js
  src/components/forms/EditContractForm.js
  src/components/forms/EditPatternForm.js
  src/components/forms/PrinterPatternForm.js
  src/pages/EditPattern.js
  src/pages/PatternList.js
  src/pages/ViewContract.js
  src/pages/ViewPattern.js
  src/style/components/printerPatternForm.css
  src/style/pages/patternList.css
  src/style/pages/viewPattern.css
  src/tests/components/StatusButton.test.js
  src/tests/forms/ContractForm.test.js
  src/tests/forms/CounterRoutineForm.test.js
  src/tests/forms/EditContractForm.test.js
  src/tests/pages/ContractList.test.js
  src/tests/pages/CreateContract.test.js
  src/tests/pages/PatternList.test.js
  src/tests/pages/ViewContract.test.js
  src/tests/services/contractService.test.js
Labels: MAJOR RELEASE
